name: iOS Deploy

on:
 workflow_dispatch:
 push:
   branches: [ master ]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Set up Fastlane
      run: bundle install

    - name: Build & Deploy to Firebase
      run: bundle exec fastlane firebase
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        FIREBASE_TESTERS: ${{ secrets.FIREBASE_TESTERS }}
        FIREBASE_TEST_GROUP: ${{ secrets.FIREBASE_TEST_GROUP }}
